name: Generate Release Notes and Create Release
description: Install gen_release_notes.sh, generate changelog and create GitHub release

inputs:
  rng_version:
    description: "Release Notes Generator version (e.g., v1.0.3 or 1.0.3)"
    required: true

outputs:
  changelog:
    description: "Generated changelog content"
    value: ${{ steps.changelog.outputs.changelog }}
  is_empty:
    description: "True if changelog is empty"
    value: ${{ steps.changelog.outputs.is_empty }}

runs:
  using: composite
  steps:
    - name: Git clone this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download gen_release_notes.sh
      shell: bash
      run: |
        VERSION="${{ inputs.rng_version }}"
        if [[ $VERSION != v* ]]; then VERSION="v$VERSION"; fi
        curl -f -L -o gen_release_notes.sh \
          "https://raw.githubusercontent.com/Greewil/release-notes-generator/${VERSION}/gen_release_notes.sh"
        chmod +x gen_release_notes.sh

    - name: Generate release notes
      id: changelog
      shell: bash
      run: |
        ./gen_release_notes.sh -i .. -lt -f changelog.md
        [ -f "changelog.md" ] && CHANGELOG=$(cat changelog.md) || CHANGELOG=''
        echo "$CHANGELOG"
        echo 'changelog<<EOF' >> "$GITHUB_OUTPUT"
        echo "$CHANGELOG" >> "$GITHUB_OUTPUT"
        echo 'EOF' >> "$GITHUB_OUTPUT"

        [ -f 'changelog.md' ] && echo "is_empty=false" >> "$GITHUB_OUTPUT"
        [ -f 'changelog.md' ] || echo "is_empty=true" >> "$GITHUB_OUTPUT"
